url="https://api.mgmt.cloud.vmware.com"
region_1="ap-southeast-1"
region_2="ap-southeast-2"
project_name="testProject"
project_desc="testProject description here"
cloud_account="SDDC ANZ AWS"
zone_apse1="ANZ AWS APSE1"
zone_apse2="ANZ AWS APSE2"